"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";

import { useGary, GaryConversation, F } from "@/components/ui/GaryChat";
import ThoughtBubble from "@/components/ui/ThoughtBubble";

/**
 * Gary, pacing the top edge of the card, and stopping to talk.
 *
 * The pacing itself: his speed is not chosen, it is derived. The sprite
 * advances a fixed distance per walk cycle, so if the element moves at any
 * other rate his feet slide along the edge. Everything below exists to make
 * travel-per-second equal stride-per-cycle.
 *
 *   stride  98px at source scale, where the figure is 177px tall
 *           (measured off the drawings: 49px step length, two steps per cycle)
 *
 * Both sheets are cropped so their bottom row is his lowest foot pixel, which
 * is why bottom: 100% lands him exactly on the card's edge at any size.
 *
 * Stopping to talk is the interesting part. He walks under a CSS animation, so
 * nothing in JS knows where he is at any moment. Rather than reimplement the
 * walk in JS to find out, the running animations are paused through the Web
 * Animations API, which freezes him mid-stride exactly where he was and, more
 * usefully, remembers his progress. Resuming is then just play(): he carries on
 * from the step he stopped on instead of teleporting back to the left edge.
 *
 * While he is stopped, the walking sprite is left mounted but invisible (so its
 * paused animations keep their place) and a second, front-facing sprite is
 * drawn at the position he stopped at. The two sheets are generated by
 * make-pacer.mjs and make-facing.mjs from the same source at the same scale and
 * baseline, so the swap reads as him turning to face you rather than changing.
 */

const FRAMES = 8;
const FPS = 12;
const STRIDE_RATIO = 98 / 177; // distance per cycle, as a fraction of his height
const HEIGHT = 72; // display height of one cell, px
const ASPECT = 114 / 144;
const WIDTH = HEIGHT * ASPECT;

/**
 * The standing sheet is Patrick's two drawn head-on poses, the same pair the
 * pointing figure on the front page uses. They alternate slowly, which reads as
 * him gesturing while he talks rather than animating.
 */
const FACING_FRAMES = 2;
const FACING_CYCLE = 1.6; // seconds for both poses

/** Where he stands to say hello, before he has started pacing. */
const GREET_X = 0.12;
/** How long the greeting holds before it drifts away on its own, ms. */
const GREET_MS = 10000;
/** And how long it takes to fade once it starts going. */
const GREET_FADE_MS = 700;

/** The greeting is one line of handwriting, so it stays small. */
const GREET_W = 320;
/** The conversation reads better wide and shallow, roughly 16:9. */
const CHAT_W = 480;
/** Clearance between bubble and Gary, so the trail puffs land in the gap
    rather than on top of his head. */
const GAP = 48;
/** Roughly how tall a greeting runs, for the does-it-fit-above test. */
const GREET_H = 84;
/** A conversation needs about this much height to be worth having. */
const CHAT_H = Math.round((CHAT_W * 9) / 16);
/** Narrower than this and the card is a phone: no room to speak beside him. */
const MIN_TRACK_W = 420;

export default function GaryPacing() {
  const track = useRef<HTMLDivElement>(null);
  const walker = useRef<HTMLDivElement>(null);
  const [seconds, setSeconds] = useState(0);

  const { enabled, greeting, greeted, markGreeted, open, setOpen } = useGary();

  const [greetingNow, setGreetingNow] = useState(false);
  /** Fading out rather than blinking out of existence. */
  const [leaving, setLeaving] = useState(false);
  /** Where he stopped, in px from the left of the track. Null while walking. */
  const [anchor, setAnchor] = useState<number | null>(null);
  const [trackW, setTrackW] = useState(0);
  const [roomAbove, setRoomAbove] = useState(0);

  const stopped = greetingNow || open;

  useEffect(() => {
    if (!enabled || greeted || !greeting) return;
    setGreetingNow(true);
    const fade = setTimeout(() => setLeaving(true), GREET_MS);
    const gone = setTimeout(() => {
      setGreetingNow(false);
      setLeaving(false);
      markGreeted();
    }, GREET_MS + GREET_FADE_MS);
    return () => {
      clearTimeout(fade);
      clearTimeout(gone);
    };
  }, [enabled, greeted, greeting, markGreeted]);

  useEffect(() => {
    const el = track.current;
    if (!el) return;

    const measure = () => {
      setTrackW(el.clientWidth);
      setRoomAbove(el.getBoundingClientRect().top);
      const width = el.clientWidth - WIDTH;
      if (width <= 0) return;
      // one cycle covers STRIDE_RATIO of his height, and a cycle takes
      // FRAMES/FPS seconds, so this is the only speed his feet agree with
      const speed = (STRIDE_RATIO * HEIGHT) / (FRAMES / FPS);
      setSeconds((width / speed) * 2); // there and back
    };

    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    window.addEventListener("scroll", measure, { passive: true });
    return () => {
      ro.disconnect();
      window.removeEventListener("scroll", measure);
    };
  }, []);

  // Freeze him where he is, or let him go again.
  useEffect(() => {
    const el = walker.current;
    const tr = track.current;
    if (!el || !tr) return;

    if (stopped) {
      // Before the walk has started he has no animation to read, so fall back
      // to the spot the greeting is written for.
      const anims = el.getAnimations();
      if (anims.length && seconds) {
        const x = el.getBoundingClientRect().left - tr.getBoundingClientRect().left;
        setAnchor(x);
        anims.forEach((a) => a.pause());
      } else {
        setAnchor(tr.clientWidth * GREET_X);
      }
    } else {
      setAnchor(null);
      el.getAnimations().forEach((a) => a.play());
    }
  }, [stopped, seconds]);

  const openChat = useCallback(() => {
    setGreetingNow(false);
    setLeaving(false);
    markGreeted();
    setOpen(true);
  }, [markGreeted, setOpen]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, setOpen]);

  // The bubble is centred on him and clamped inside the card's width, so it is
  // always fully on screen however close to an edge he stopped.
  const wanted = open ? CHAT_W : GREET_W;
  const bubbleW = Math.min(wanted, trackW || wanted);
  const centre = (anchor ?? 0) + WIDTH / 2;
  const bubbleLeft = Math.max(
    0,
    Math.min(centre - bubbleW / 2, Math.max(0, trackW - bubbleW)),
  );
  /**
   * The card sits centred in the viewport, which on a laptop leaves only about
   * 150px of sky above it. A greeting fits in that; a conversation does not.
   * So the bubble flips the way a tooltip does, and when it flips it hangs
   * below him over the card, with the tail pointing back up at his feet. It is
   * still him speaking, and it is only in the way while the chat is open.
   */
  /* roomAbove is the viewport distance to the top of the track, and the track
     is exactly his height, so it already measures the sky above his head. Do
     not subtract HEIGHT again here: doing so double counts him and sends the
     greeting down over the card when there was room for it all along. */
  const wantedH = open ? CHAT_H : GREET_H;
  const above = roomAbove - GAP >= wantedH;
  /* Hold the 16:9 even when the card is too narrow for the full width, so it
     stays a wide screen rather than becoming a square again. */
  const chatH = Math.round((bubbleW * 9) / 16);
  const bubbleH = open
    ? above
      ? Math.min(Math.max(roomAbove - GAP, chatH), 420)
      : chatH
    : undefined;

  /** A phone: nothing sensible fits beside a 57px figure. */
  const compact = open && trackW > 0 && trackW < MIN_TRACK_W;

  return (
    <>
      <div
        ref={track}
        aria-hidden={!enabled}
        style={{
          position: "absolute",
          left: 0,
          right: 0,
          bottom: "100%",
          height: HEIGHT,
          containerType: "inline-size",
          pointerEvents: "none",
          overflow: "hidden",
        }}
      >
        {/* The walker stays mounted while he is stopped. Its animations are
            paused, not cancelled, which is what remembers his place. */}
        <div
          ref={walker}
          data-gary
          role={enabled && !stopped ? "button" : undefined}
          tabIndex={enabled && !stopped ? 0 : undefined}
          aria-label={enabled && !stopped ? "Chat with Gary" : undefined}
          onClick={enabled ? openChat : undefined}
          onKeyDown={
            enabled
              ? (e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    openChat();
                  }
                }
              : undefined
          }
          style={
            {
              position: "absolute",
              bottom: 0,
              width: WIDTH,
              height: HEIGHT,
              "--gary-w": `${WIDTH}px`,
              backgroundImage: "url(/assets/gary-pace.png)",
              backgroundSize: `${WIDTH * FRAMES}px ${HEIGHT}px`,
              animation: seconds
                ? `gary-step ${FRAMES / FPS}s steps(${FRAMES}) infinite,` +
                  ` gary-pace ${seconds}s linear infinite`
                : "none",
              opacity: stopped ? 0 : 1,
              pointerEvents: enabled && !stopped ? "auto" : "none",
              cursor: enabled ? "pointer" : undefined,
            } as React.CSSProperties
          }
        />

        {/* Turned to face you, standing where he stopped. */}
        {stopped && anchor !== null && (
          <div
            data-gary-facing
            role="button"
            tabIndex={0}
            aria-label={open ? "Close chat" : "Chat with Gary"}
            onClick={open ? () => setOpen(false) : openChat}
            onKeyDown={(e) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                if (open) setOpen(false);
                else openChat();
              }
            }}
            style={
              {
                position: "absolute",
                bottom: 0,
                left: anchor,
                width: WIDTH,
                height: HEIGHT,
                "--gary-w": `${WIDTH}px`,
                "--gary-cells": -FACING_FRAMES,
                backgroundImage: "url(/assets/gary-facing.png)",
                backgroundSize: `${WIDTH * FACING_FRAMES}px ${HEIGHT}px`,
                animation: `gary-step ${FACING_CYCLE}s steps(${FACING_FRAMES}) infinite`,
                pointerEvents: "auto",
                cursor: "pointer",
              } as React.CSSProperties
            }
          />
        )}
      </div>

      {/* Outside the track, which clips at his own height and would cut off
          anything he says. The bubble is drawn rather than boxed: see
          ThoughtBubble, which builds the outline from the measured size so the
          puffs stay round whether he is saying one line or holding a whole
          conversation. */}
      {enabled && stopped && anchor !== null && !compact && (
        <ThoughtBubble
          role={open ? "dialog" : undefined}
          ariaLabel={open ? "Chat with Gary" : undefined}
          tail={above ? "down" : "up"}
          tailX={Math.max(16, Math.min(centre - bubbleLeft, bubbleW - 16))}
          style={{
            position: "absolute",
            /* Above his head when it fits, otherwise hanging below his feet
               over the card. Either way the trail leads back to him. */
            ...(above
              ? { bottom: `calc(100% + ${HEIGHT + GAP}px)` }
              : { top: GAP }),
            left: bubbleLeft,
            width: bubbleW,
            height: bubbleH,
            zIndex: 20,
            opacity: leaving ? 0 : 1,
            transition: `opacity ${GREET_FADE_MS}ms ease`,
          }}
        >
          {open ? (
            <>
              <header
                className="flex items-center justify-between"
                style={{ paddingBottom: "0.35rem" }}
              >
                <span
                  style={{
                    color: F.ink,
                    fontFamily: "var(--font-hand)",
                    fontSize: "1.15rem",
                    lineHeight: 1,
                  }}
                >
                  Gary
                </span>
                <button
                  onClick={() => setOpen(false)}
                  aria-label="Close"
                  style={{ color: F.inkFaint, fontSize: "1rem", lineHeight: 1 }}
                >
                  ×
                </button>
              </header>
              <GaryConversation />
            </>
          ) : (
            /* His own line, in the site's handwriting, because it is the one
               thing on the page he actually says out loud. */
            <button
              onClick={openChat}
              style={{
                display: "block",
                textAlign: "left",
                color: F.ink,
                fontFamily: "var(--font-hand)",
                fontSize: "1.15rem",
                lineHeight: 1.3,
                cursor: "pointer",
              }}
            >
              {greeting}
            </button>
          )}
        </ThoughtBubble>
      )}

      {/* On a phone there is no room beside him, so the conversation falls back
          to a sheet at the bottom of the screen.

          Portalled to the body deliberately. This sheet is position: fixed, and
          a fixed element inside a transformed ancestor is positioned against
          that ancestor rather than the viewport. The card is wrapped in a
          BlurFade, which animates a transform, so rendering it in place put the
          sheet in the middle of the card instead of at the bottom of the
          screen. */}
      {enabled && open && compact && typeof document !== "undefined" && createPortal(
        <div
          role="dialog"
          aria-label="Chat with Gary"
          className="fixed z-50 flex flex-col"
          style={{
            left: "0.75rem",
            right: "0.75rem",
            bottom: "0.75rem",
            height: "min(60svh, 380px)",
            backgroundColor: F.card,
            border: `1px solid ${F.edge}`,
            borderRadius: "0.8rem",
            boxShadow: F.shadow,
            overflow: "hidden",
          }}
        >
          <header
            className="flex items-center justify-between px-3 py-2"
            style={{ borderBottom: `1px solid ${F.edgeSoft}` }}
          >
            <span style={{ color: F.ink, fontSize: "0.85rem", fontWeight: 600 }}>
              Gary
            </span>
            <button
              onClick={() => setOpen(false)}
              aria-label="Close"
              style={{ color: F.inkFaint, fontSize: "1.1rem", lineHeight: 1 }}
            >
              ×
            </button>
          </header>
          <GaryConversation />
        </div>,
        document.body,
      )}
    </>
  );
}
