"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";

import {
  claimConversation,
  useGary,
  GaryConversation,
  F,
} from "@/components/ui/GaryChat";
import ThoughtBubble from "@/components/ui/ThoughtBubble";
import {
  fitWidth,
  H_MIN,
  LOBE_BLEED,
  placeBubble,
  rollDraw,
  type Bounds,
  type BubbleMode,
  type Draw,
} from "@/lib/bubblePlacement";

/**
 * Gary, pacing a horizontal edge, and stopping to talk.
 *
 * Three pages use him: the top of the card on /fun, and the rule under the
 * heading on the portfolio and in the garden. He used to be /fun's alone, and
 * the other two had a GaryStanding who stood at the end of the rule waiting to
 * be clicked. That was the wrong character. He is the same drawing on every
 * page, so he should behave the same way on every page, and standing still on
 * two of four made those two read as the pages Gary had not got round to.
 *
 * What differs between them is passed in rather than sniffed: his line, the
 * key it is remembered under, whether to paint his knockout, what is in his
 * sky. Nothing in here branches on pathname, and nothing should start to.
 *
 * The pacing itself: his speed is not chosen, it is derived. The sprite
 * advances a fixed distance per walk cycle, so if the element moves at any
 * other rate his feet slide along the edge. Everything below exists to make
 * travel-per-second equal stride-per-cycle.
 *
 *   stride  98px at source scale, where the figure is 177px tall
 *           (measured off the drawings: 49px step length, two steps per cycle)
 *
 * Both sheets are cropped so their bottom row is his lowest foot pixel, which
 * is why bottom: 100% lands him exactly on the top edge of whatever wrapper
 * he is mounted in, at any size.
 *
 * Stopping to talk is the interesting part. He walks under a CSS animation, so
 * nothing in JS knows where he is at any moment. Rather than reimplement the
 * walk in JS to find out, the running animations are paused through the Web
 * Animations API, which freezes him mid-stride exactly where he was and, more
 * usefully, remembers his progress. Resuming is then just play(): he carries on
 * from the step he stopped on instead of teleporting back to the left edge.
 *
 * While he is stopped, the walking sprite is left mounted but invisible (so its
 * paused animations keep their place) and a second, front-facing sprite is
 * drawn at the position he stopped at. The two sheets are generated by
 * make-pacer.mjs and make-facing.mjs from the same source at the same scale and
 * baseline, so the swap reads as him turning to face you rather than changing.
 */

const FRAMES = 8;
const FPS = 12;
const STRIDE_RATIO = 98 / 177; // distance per cycle, as a fraction of his height
const HEIGHT = 72; // display height of one cell, px
/** His height, for a page that has to hold open the sky he walks in. */
export const GARY_HEIGHT = HEIGHT;
const ASPECT = 114 / 144;
const WIDTH = HEIGHT * ASPECT;

/**
 * The standing sheet is Patrick's two drawn head-on poses, the same pair the
 * pointing figure on the front page uses. They alternate slowly, which reads as
 * him gesturing while he talks rather than animating.
 */
const FACING_FRAMES = 2;
const FACING_CYCLE = 1.6; // seconds for both poses

/* Where his mouth is inside one cell, as a fraction of the cell.
   
   Measured off gary-facing.png rather than estimated: in the 114x144 cell his
   head circle runs rows 17-95 and the smile spans rows 72-82 across columns
   40-85, so its centre is (61, 77). Both sheets are drawn from the same source
   at the same scale and baseline, so one pair of fractions covers him standing
   and walking alike. If the drawing is redrawn, re-measure; do not nudge these
   until the trail looks right. */
const MOUTH_X = 61 / 114;
const MOUTH_Y = 77 / 144;

/* How far off his mouth the trail's column runs, so the puffs come down past
   his cheek instead of over his face. His head reaches 21px either side of his
   mouth at this size and the fattest puff in a trail measures 9px, so 36
   leaves the widest one about 6px off his cheek and the small ones nearer. Set
   wider than this and the trail reads as passing him rather than reaching him:
   at 48 the last puff landed 46px out, beside his eyes. */
const MOUTH_CLEAR_X = 36;

/** Where he stands to say hello, before he has started pacing. */
const GREET_X = 0.12;
/** How long the greeting holds before it drifts away on its own, ms. */
const GREET_MS = 10000;
/** And how long it takes to fade once it starts going. */
const GREET_FADE_MS = 700;

/** The greeting is one line of handwriting, so it stays small. */
const GREET_W = 320;
/** The conversation reads better wide and shallow, roughly 16:9. */
const CHAT_W = 480;
/** Roughly how tall a greeting runs. Only the first guess: the greeting box
    is auto height, and the bubble reports its real measured height back
    (ThoughtBubble's onSize), after which the placement is redone off the
    true box the outline is built from. */
const GREET_H = 84;
/** Narrower than this and the card is a phone: no room to speak beside him. */
const MIN_TRACK_W = 420;

/* There is deliberately no gap constant in this file. How far the bubble
   stands off him is `placeBubble` in src/lib/bubblePlacement.ts, measured
   off the trail actually being drawn, and it is the same rule /story uses.
   A fixed 48px lived here once, after /story had switched to measuring, and
   the next change to the tail art put the last puff on his head. */

/** What the bubble has to know about the page: the track's width and
    position, and the viewport, all read in one measure. */
type Geo = {
  trackW: number;
  trackLeft: number;
  /** Viewport distance to the top of the track, i.e. to the top of his head. */
  roomAbove: number;
  vw: number;
  vh: number;
};

export default function GaryPacing({
  /**
   * The line he says on arrival, already read out of content/gary.md by the
   * server component that renders him. Defaults to the site greeting, which is
   * /fun's. Empty string means this page has nothing for him to say, and he
   * goes straight to pacing without a bubble.
   */
  greeting: greetingProp,
  /**
   * Which page this is, for remembering that its greeting has been said. The
   * pathname is the obvious value and every caller passes it; it is a prop
   * rather than a usePathname() call so a page can hold its own key steady
   * across a route change if it ever needs to.
   */
  greetKey = "/fun",
  /**
   * Paint his knockout silhouette under him. On /fun he walks across the roof
   * of the house, and without it the drawing behind shows through his head. He
   * has nothing behind him on the portfolio or in the garden, and the knockout
   * is a flat #121212 rather than a theme colour, so painting it there would
   * put a faint dark patch on the page for no gain.
   */
  knockout = true,
  /**
   * How far down the viewport the painted drawing must stay, in px.
   *
   * /fun has no nav, so nothing is in his sky and the default is 0. The
   * portfolio and the garden are under a 54px sticky nav, and his greeting
   * needs roughly 150px above his head: without this the box solves into the
   * top of the viewport and the nav is painted over the top of it. Given to
   * the shared solver as the bounds' top edge, so a greeting that will not
   * fit under the ceiling moves or shrinks by the same rules as everything
   * else rather than being clipped.
   */
  ceiling = 0,
  /**
   * Which sides the greeting may take. The conversation is unaffected: it is a
   * box the visitor opened and it may go above or below as it always has.
   *
   * /fun keeps "above", and the long note further down explains why the
   * greeting gets one side rather than being allowed to flip: nobody asked for
   * it, so it must not land on the card. The portfolio and the garden want
   * "right" for the mirror-image reason. Their sky is not empty, it has the
   * page's <h1> in it, and a greeting solved into the space above his head
   * covers the one word telling you which page you are on. The band beside him
   * between the heading and the rule is genuinely empty, so he speaks into
   * that instead, and the page costs no extra height to make room for ten
   * seconds of handwriting.
   */
  greetModes = ["above"],
}: {
  greeting?: string;
  greetKey?: string;
  knockout?: boolean;
  ceiling?: number;
  greetModes?: Exclude<BubbleMode, "pinned">[];
} = {}) {
  const track = useRef<HTMLDivElement>(null);
  const walker = useRef<HTMLDivElement>(null);
  const [seconds, setSeconds] = useState(0);

  const {
    enabled,
    greeting: siteGreeting,
    hasGreeted,
    markGreeted,
    open,
    setOpen,
  } = useGary();
  const greeting = greetingProp ?? siteGreeting;
  const greeted = hasGreeted(greetKey);

  const [greetingNow, setGreetingNow] = useState(false);
  /** Fading out rather than blinking out of existence. */
  const [leaving, setLeaving] = useState(false);
  /** Where he stopped, in px from the left of the track. Null while walking. */
  const [anchor, setAnchor] = useState<number | null>(null);
  const [geo, setGeo] = useState<Geo>({
    trackW: 0,
    trackLeft: 0,
    roomAbove: 0,
    vw: 0,
    vh: 0,
  });

  const stopped = greetingNow || open;

  /* One drawing per open, rolled here rather than inside ThoughtBubble,
     because the placement needs the trail's true reach before the bubble
     exists: variant and wobble go into the placement for measuring and are
     handed down so the bubble draws exactly the shape that was measured.
     Held across the greeting growing into the conversation, so the bubble
     keeps its character while re-fitting the new box; cleared when he walks
     on, so the next stop is a fresh drawing. rollDraw honours `?bubble=N` /
     `?wobble=N` for checking every recipe deliberately. */
  const [draw, setDraw] = useState<Draw | null>(null);
  /** The side chosen last render, kept while it still fits so the bubble
      does not flip on a scroll tick. Keyed to the box it was chosen for:
      the greeting and the conversation are different boxes, so the side
      the greeting settled on is not carried into the chat, which picks
      afresh by the shared preference order and stays put from then on.
      Read and written during render, deliberately, so the very first chat
      frame already starts from a clean choice. */
  const bubbleMode = useRef<{ open: boolean; mode: BubbleMode } | null>(null);
  /** The greeting box's real height, reported by the bubble once drawn. */
  const [greetH, setGreetH] = useState<number | null>(null);
  useEffect(() => {
    if (!stopped) {
      setDraw(null);
      setGreetH(null);
      bubbleMode.current = null;
      return;
    }
    setDraw(rollDraw());
  }, [stopped]);

  /**
   * Whether to greet at all, decided once and then never revisited.
   *
   * Said is said: he is marked as having greeted the moment the line goes up,
   * not when it finishes. It used to be marked at the end of the ten seconds,
   * which was invisible while /fun was his only page and wrong as soon as it
   * was not. Clicking from the portfolio to the garden and back takes about
   * four seconds, so he greeted the portfolio again, and again, every time you
   * came back. A greeting you have already read is not a greeting.
   *
   * The ref is what makes "once" mean once. Marking greeted changes hasGreeted
   * and re-runs this effect, and the guard turns the second pass into a
   * no-op rather than a second greeting.
   */
  const decided = useRef(false);
  useEffect(() => {
    if (decided.current) return;
    if (!enabled || greeted || !greeting) return;
    /* Nothing measured yet, so wait; or measured and too narrow to draw a
       bubble in, so never. Greeting freezes him mid-walk, and on a phone the
       bubble is suppressed (see `tooNarrow`), which left him standing to
       attention for ten seconds saying nothing before he started pacing. If
       he cannot say it, he does not stop to say it. */
    if (geo.trackW === 0) return;
    if (geo.trackW < MIN_TRACK_W) return;
    decided.current = true;
    setGreetingNow(true);
    markGreeted(greetKey);
  }, [enabled, greeted, greeting, markGreeted, greetKey, geo.trackW]);

  /**
   * How long it stays up. Split from the decision above deliberately: these
   * timers must live exactly as long as the greeting is on screen, and an
   * effect that also depends on hasGreeted would tear them down and not
   * rebuild them the instant the greeting was marked as said. `greetingNow` is
   * the only thing that should be able to cancel them, so it is the only
   * dependency.
   */
  useEffect(() => {
    if (!greetingNow) return;
    const fade = setTimeout(() => setLeaving(true), GREET_MS);
    const gone = setTimeout(() => {
      setGreetingNow(false);
      setLeaving(false);
    }, GREET_MS + GREET_FADE_MS);
    return () => {
      clearTimeout(fade);
      clearTimeout(gone);
    };
  }, [greetingNow]);

  /* He is on the page, so the conversation is his and the corner panel stands
     down. Claimed for as long as he is mounted and real, not only while the
     chat is open: the panel is the fallback for pages with no Gary, and this
     is not one. */
  useEffect(() => {
    if (!enabled) return;
    return claimConversation();
  }, [enabled]);

  useEffect(() => {
    const el = track.current;
    if (!el) return;

    const measure = () => {
      const r = el.getBoundingClientRect();
      const next: Geo = {
        trackW: el.clientWidth,
        trackLeft: r.left,
        roomAbove: r.top,
        vw: window.innerWidth,
        vh: window.innerHeight,
      };
      setGeo((prev) =>
        prev.trackW === next.trackW &&
        prev.trackLeft === next.trackLeft &&
        prev.roomAbove === next.roomAbove &&
        prev.vw === next.vw &&
        prev.vh === next.vh
          ? prev
          : next,
      );
      const width = el.clientWidth - WIDTH;
      if (width <= 0) return;
      // one cycle covers STRIDE_RATIO of his height, and a cycle takes
      // FRAMES/FPS seconds, so this is the only speed his feet agree with
      const speed = (STRIDE_RATIO * HEIGHT) / (FRAMES / FPS);
      setSeconds((width / speed) * 2); // there and back
    };

    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    window.addEventListener("scroll", measure, { passive: true });
    window.addEventListener("resize", measure);
    return () => {
      ro.disconnect();
      window.removeEventListener("scroll", measure);
      window.removeEventListener("resize", measure);
    };
  }, []);

  // Freeze him where he is, or let him go again.
  useEffect(() => {
    const el = walker.current;
    const tr = track.current;
    if (!el || !tr) return;

    if (stopped) {
      // Before the walk has started he has no animation to read, so fall back
      // to the spot the greeting is written for.
      const anims = el.getAnimations();
      if (anims.length && seconds) {
        const x = el.getBoundingClientRect().left - tr.getBoundingClientRect().left;
        setAnchor(x);
        anims.forEach((a) => a.pause());
      } else {
        setAnchor(tr.clientWidth * GREET_X);
      }
    } else {
      setAnchor(null);
      el.getAnimations().forEach((a) => a.play());
    }
  }, [stopped, seconds]);

  const openChat = useCallback(() => {
    setGreetingNow(false);
    setLeaving(false);
    markGreeted(greetKey);
    setOpen(true);
  }, [markGreeted, greetKey, setOpen]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, setOpen]);

  const { trackW, trackLeft, roomAbove, vw, vh } = geo;
  const centre = (anchor ?? 0) + WIDTH / 2;

  /* The bubble is positioned inside the card's wrapper, whose top edge is
     the ground his feet stand on, so the placement is solved in wrapper
     coordinates: his feet at y = 0, his head top at y = -HEIGHT. The edges
     it must respect are the card's track sideways (the box stays over the
     card, as it always has) AND the section's clip edges, which are the
     viewport's: the section is overflow: hidden, so a lobe or a puff past
     the viewport top is sliced off, not merely out of view. The bounds are
     the painted drawing's; the shared solver keeps the layout box inside
     them by the lobes' and the trail's real reach.

     roomAbove is the viewport distance to the top of the track, and the
     track is exactly his height, so it already measures the sky above his
     head. The wrapper's top is HEIGHT below that. */
  const groundTop = roomAbove + HEIGHT;
  const bounds: Bounds = {
    left: Math.max(-trackLeft, -LOBE_BLEED),
    right: trackW + Math.min(vw - trackLeft - trackW, LOBE_BLEED),
    top: -groundTop + ceiling,
    bottom: vh - groundTop,
  };
  const bubbleW = fitWidth(open ? CHAT_W : GREET_W, bounds);
  /* Hold the 16:9 even when the card is too narrow for the full width, so it
     stays a wide screen rather than becoming a square again. The greeting
     is as tall as its handwriting: the measured height once the bubble has
     reported it, the estimate until then. */
  const bubbleH = open ? Math.round((bubbleW * 9) / 16) : (greetH ?? GREET_H);

  /**
   * The card sits centred in the viewport, which on a laptop leaves only
   * about 150px of sky above it. So the chat box flips the way a tooltip
   * does: above his head when the drawing fits there, otherwise hanging
   * below him over the card with the trail pointing back up at his feet. It
   * is a box the visitor opened, and it is only in the way while it is open.
   *
   * The greeting is not that. Nobody asked for it, it arrives on load, and
   * hanging it below him laid it straight over the photo on the card. Worse,
   * whether that happened was a matter of window height rather than anything
   * a visitor could see or change: at 1280x800 and 1536x864 there is not
   * enough sky for the box plus its own trail, so it fell to `below` every
   * single time; at 1920x1080 it never did. So the greeting is allowed one
   * side only. When it truly will not fit, the shared solver pins it inside
   * the bounds, which puts it at the top of the sky with the trail dodged
   * sideways past his head, and it is still above him and still off the card.
   *
   * Which side, and how far off him, is the shared rule; this page only says
   * the sides it allows.
   */
  const placed =
    draw && trackW > 0
      ? placeBubble({
          speaker: {
            x: centre,
            top: -HEIGHT,
            bottom: 0,
            halfW: WIDTH / 2,
            /* His feet are at y = 0 and the cell's top edge at y = -HEIGHT,
               so the mouth is that far down the cell from the top. The trail
               lands level with it rather than stopping above his head. */
            mouth: {
              x: centre - WIDTH / 2 + WIDTH * MOUTH_X,
              y: -HEIGHT + HEIGHT * MOUTH_Y,
              clearX: MOUTH_CLEAR_X,
            },
          },
          draw,
          w: bubbleW,
          hMax: bubbleH,
          hMin: open ? H_MIN : bubbleH,
          bounds,
          modes: open ? ["above", "below"] : greetModes,
          prev:
            bubbleMode.current && bubbleMode.current.open === open
              ? bubbleMode.current.mode
              : null,
        })
      : null;
  if (placed) bubbleMode.current = { open, mode: placed.mode };

  /** A phone. Nothing sensible fits beside a 57px figure, and nothing fits
      above him either: the card starts about 48px down the screen, so the sky
      over his head is shorter than he is, against the ~150px a greeting and
      its trail need. Every placement there lands on the photo or on Gary
      himself, so on a narrow screen he simply does not draw a bubble. The
      chat still opens, as the sheet below; the greeting is decoration and it
      is better missing than painted over Patrick's family. */
  const tooNarrow = trackW > 0 && trackW < MIN_TRACK_W;
  const compact = open && tooNarrow;

  return (
    <>
      <div
        ref={track}
        aria-hidden={!enabled}
        style={{
          position: "absolute",
          left: 0,
          right: 0,
          bottom: "100%",
          height: HEIGHT,
          containerType: "inline-size",
          pointerEvents: "none",
          overflow: "hidden",
        }}
      >
        {/* The walker stays mounted while he is stopped. Its animations are
            paused, not cancelled, which is what remembers his place. */}
        <div
          ref={walker}
          data-gary
          role={enabled && !stopped ? "button" : undefined}
          tabIndex={enabled && !stopped ? 0 : undefined}
          aria-label={enabled && !stopped ? "Chat with Gary" : undefined}
          onClick={enabled ? openChat : undefined}
          onKeyDown={
            enabled
              ? (e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    openChat();
                  }
                }
              : undefined
          }
          style={
            {
              position: "absolute",
              bottom: 0,
              width: WIDTH,
              height: HEIGHT,
              "--gary-w": `${WIDTH}px`,
              /* Two layers, his sprite over his own knockout. The knockout is
                 the same figure filled in the colour of the ground, so scenery
                 behind him is covered by his silhouette instead of showing
                 through his head. One background-position drives both layers,
                 so gary-step keeps them in register for free. Built by
                 scripts/dev/make-solid.mjs. Dropped where there is nothing
                 behind him to knock out: see the `knockout` prop. */
              backgroundImage: knockout
                ? "url(/assets/gary-pace.png), url(/assets/gary-pace-solid.png)"
                : "url(/assets/gary-pace.png)",
              backgroundSize: `${WIDTH * FRAMES}px ${HEIGHT}px`,
              animation: seconds
                ? `gary-step ${FRAMES / FPS}s steps(${FRAMES}) infinite,` +
                  ` gary-pace ${seconds}s linear infinite`
                : "none",
              opacity: stopped ? 0 : 1,
              pointerEvents: enabled && !stopped ? "auto" : "none",
              cursor: enabled ? "pointer" : undefined,
            } as React.CSSProperties
          }
        />

        {/* Turned to face you, standing where he stopped. */}
        {stopped && anchor !== null && (
          <div
            data-gary-facing
            role="button"
            tabIndex={0}
            aria-label={open ? "Close chat" : "Chat with Gary"}
            onClick={open ? () => setOpen(false) : openChat}
            onKeyDown={(e) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                if (open) setOpen(false);
                else openChat();
              }
            }}
            style={
              {
                position: "absolute",
                bottom: 0,
                left: anchor,
                width: WIDTH,
                height: HEIGHT,
                "--gary-w": `${WIDTH}px`,
                "--gary-cells": -FACING_FRAMES,
                backgroundImage: knockout
                  ? "url(/assets/gary-facing.png), url(/assets/gary-facing-solid.png)"
                  : "url(/assets/gary-facing.png)",
                backgroundSize: `${WIDTH * FACING_FRAMES}px ${HEIGHT}px`,
                animation: `gary-step ${FACING_CYCLE}s steps(${FACING_FRAMES}) infinite`,
                pointerEvents: "auto",
                cursor: "pointer",
              } as React.CSSProperties
            }
          />
        )}
      </div>

      {/* Outside the track, which clips at his own height and would cut off
          anything he says. The bubble is drawn rather than boxed: see
          ThoughtBubble, which builds the outline from the measured size so the
          puffs stay round whether he is saying one line or holding a whole
          conversation. */}
      {enabled && stopped && anchor !== null && placed && draw && !tooNarrow && (
        <ThoughtBubble
          role={open ? "dialog" : undefined}
          ariaLabel={open ? "Chat with Gary" : undefined}
          tail={placed.tail}
          tailX={placed.tailX}
          variant={draw.variant}
          wobble={draw.wobble}
          onSize={open ? undefined : ({ h }) => setGreetH(h)}
          style={{
            position: "absolute",
            /* Above his head when it fits, otherwise hanging below his feet
               over the card. Either way the trail leads back to him. */
            left: placed.left,
            top: placed.top,
            width: placed.w,
            height: open ? placed.h : undefined,
            zIndex: 20,
            opacity: leaving ? 0 : 1,
            transition: `opacity ${GREET_FADE_MS}ms ease`,
          }}
        >
          {open ? (
            <>
              <header
                className="flex items-center justify-between"
                style={{ paddingBottom: "0.35rem" }}
              >
                <span
                  style={{
                    color: F.ink,
                    fontFamily: "var(--font-hand)",
                    fontSize: "1.15rem",
                    lineHeight: 1,
                  }}
                >
                  Gary
                </span>
                <button
                  onClick={() => setOpen(false)}
                  aria-label="Close"
                  style={{ color: F.inkFaint, fontSize: "1rem", lineHeight: 1 }}
                >
                  ×
                </button>
              </header>
              <GaryConversation greeting={greeting} />
            </>
          ) : (
            /* His own line, in the site's handwriting, because it is the one
               thing on the page he actually says out loud. */
            <button
              onClick={openChat}
              style={{
                display: "block",
                textAlign: "left",
                color: F.ink,
                fontFamily: "var(--font-hand)",
                fontSize: "1.15rem",
                lineHeight: 1.3,
                cursor: "pointer",
              }}
            >
              {greeting}
            </button>
          )}
        </ThoughtBubble>
      )}

      {/* On a phone there is no room beside him, so the conversation falls back
          to a sheet at the bottom of the screen.

          Portalled to the body deliberately. This sheet is position: fixed, and
          a fixed element inside a transformed ancestor is positioned against
          that ancestor rather than the viewport. The card is wrapped in a
          BlurFade, which animates a transform, so rendering it in place put the
          sheet in the middle of the card instead of at the bottom of the
          screen. */}
      {enabled && open && compact && typeof document !== "undefined" && createPortal(
        <div
          role="dialog"
          aria-label="Chat with Gary"
          className="fixed z-50 flex flex-col"
          style={{
            left: "0.75rem",
            right: "0.75rem",
            bottom: "0.75rem",
            height: "min(60svh, 380px)",
            backgroundColor: F.card,
            border: `1px solid ${F.edge}`,
            borderRadius: "0.8rem",
            boxShadow: F.shadow,
            overflow: "hidden",
          }}
        >
          <header
            className="flex items-center justify-between px-3 py-2"
            style={{ borderBottom: `1px solid ${F.edgeSoft}` }}
          >
            <span style={{ color: F.ink, fontSize: "0.85rem", fontWeight: 600 }}>
              Gary
            </span>
            <button
              onClick={() => setOpen(false)}
              aria-label="Close"
              style={{ color: F.inkFaint, fontSize: "1.1rem", lineHeight: 1 }}
            >
              ×
            </button>
          </header>
          <GaryConversation greeting={greeting} />
        </div>,
        document.body,
      )}
    </>
  );
}
